version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    container_name: app
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - REDIS_URL=${REDIS_URL}
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - ALL_PROXY=socks5://host.docker.internal:1080
    dns:
      - 8.8.8.8
      - 1.1.1.1

  worker:
    build: .
    container_name: worker
    command: rq worker --url ${REDIS_URL}
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - REDIS_URL=${REDIS_URL}
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - ALL_PROXY=socks5://host.docker.internal:1080
    dns:
      - 8.8.8.8
      - 1.1.1.1

  rqscheduler:
    build: .
    container_name: rqscheduler
    command: rqscheduler --url ${REDIS_URL} --interval 60
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - REDIS_URL=${REDIS_URL}
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - ALL_PROXY=socks5://host.docker.internal:1080
    dns:
      - 8.8.8.8
      - 1.1.1.1

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
